# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: adventure-game-skill
      # MONGO_INITDB_ROOT_USERNAME: desired username
      # MONGO_INITDB_ROOT_PASSWORD: desired pass
    volumes: ## leave this volume
      - db-data:/data/db 

  skill: 
    build: ./adventure-game-skill
    restart: always
    ports:
      - 443:3000
    depends_on:
      - db
    environment:
      NODE_ENV: ${ENV}

  notification_server: 
    build: ./notifications-service
    restart: always
    environment:
      NODE_ENV: ${ENV}
      AMAZON_API_CLIENT_ID: ${CLIENT_ID}
      AMAZON_API_CLIENT_ID_SECRET: ${CLIENT_ID_SECRET}

  transmedia_server: 
    build: ./transmedia-service
    restart: always
    ports:
      - 80:5000
    depends_on:
      - db
    environment:
      NODE_ENV: ${ENV}

volumes:
  db-data: